In [2]:
import torch
import torch.nn as nn

In [3]:
# 定义全连接层
linear= nn.Linear(5,2)

In [4]:
# 1. 常数初始化
nn.init.zeros_(linear.weight)
print(linear.weight)


Parameter containing:
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], requires_grad=True)


In [5]:
nn.init.ones_(linear.weight)
print(linear.weight)

Parameter containing:
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], requires_grad=True)


In [6]:
nn.init.constant_(linear.weight, 10)
print(linear.weight)

Parameter containing:
tensor([[10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.]], requires_grad=True)


In [7]:
# 2. 秩初始化
nn.init.eye_(linear.weight)
print(linear.weight)

Parameter containing:
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.]], requires_grad=True)


In [8]:
# 3.正态分布初始化
nn.init.normal_(linear.weight, mean=0, std=0.01)
print(linear.weight)

Parameter containing:
tensor([[-0.0038,  0.0116,  0.0057,  0.0027,  0.0050],
        [-0.0036,  0.0074,  0.0007, -0.0207, -0.0040]], requires_grad=True)


In [9]:
# 4. 均匀分布初始化
nn.init.uniform_(linear.weight, a=-3, b=3)
print(linear.weight)

Parameter containing:
tensor([[-1.8225,  1.8355,  2.2414,  1.1520,  2.3786],
        [-0.4745,  2.7577,  2.2514, -0.3860,  2.5342]], requires_grad=True)


In [10]:
# 5.Xavier初始化
nn.init.xavier_uniform_(linear.weight)
print(linear.weight)


Parameter containing:
tensor([[ 0.4424,  0.1516, -0.8113, -0.2416, -0.0556],
        [-0.3168, -0.6796, -0.7404,  0.0174, -0.2337]], requires_grad=True)


In [11]:
nn.init.xavier_normal_(linear.weight)
print(linear.weight)

Parameter containing:
tensor([[ 0.3703,  0.8017, -0.5840, -0.1448, -0.2760],
        [ 0.9483, -0.0619,  0.6071, -0.1728, -0.6821]], requires_grad=True)


In [12]:
# He初始化
nn.init.kaiming_uniform_(linear.weight,a=0)
print(linear.weight)

Parameter containing:
tensor([[ 0.2196, -0.4624, -0.6310, -0.0953, -0.2120],
        [-0.4201, -0.8701, -0.6591,  0.7405,  0.7146]], requires_grad=True)


In [13]:
nn.init.kaiming_normal_(linear.weight,a=0.01)
print(linear.weight)

Parameter containing:
tensor([[ 1.0136,  0.1883, -0.0494,  0.4270,  0.8006],
        [ 0.0776, -0.4087,  0.8031,  0.6446,  0.1859]], requires_grad=True)


In [15]:
input=torch.randn(1,5,device='cuda')
print(input.device)

cuda:0


In [16]:
input=torch.tensor([[1,2,3],[4,5,6]],device='cuda')
print(input.device)


cuda:0


In [17]:
input=torch.tensor([[1,2,3],[4,5,6]],device='cpu').to(device=torch.device('cuda'))
print(input.device)

cuda:0
