In [1]:
import torch
import torch.nn as nn
from torch.nn import CrossEntropyLoss

In [2]:
input=torch.randn(6,8)
print(input)

tensor([[ 0.3356, -0.9611,  0.2197,  0.1391,  0.6012, -1.4295, -1.3448,  1.1593],
        [ 1.1444,  0.2451,  0.3926,  0.3838,  1.4031,  1.2069, -0.6075,  0.9659],
        [ 0.8975, -1.1666, -0.2226,  0.7836,  1.2515,  1.4339,  0.5889, -0.7621],
        [ 0.2530,  0.1872, -2.8318, -0.5471,  0.6356, -0.4105, -0.3793, -1.1067],
        [ 2.4381, -0.5450,  0.8803, -1.7885, -0.1271, -0.5610,  0.4272,  1.7107],
        [-0.3365,  0.5999, -0.2267, -0.4430, -0.3874, -0.4544, -1.4904, -0.9195]])


In [3]:
# 目标值，六个数据的类型标签
target=torch.tensor([1,0,3,7,5,2])
print(target)

tensor([1, 0, 3, 7, 5, 2])


In [4]:
# 定义损失函数
loss = CrossEntropyLoss()
print(loss(input,target))

tensor(2.6101)


In [5]:
# 2. 独热编码
input=torch.randn(6,8)
print(input)


tensor([[ 0.3320,  0.3491,  1.5440,  1.0665, -0.0376,  0.4433, -1.1334,  0.7460],
        [-0.5877,  0.1196, -0.1567, -1.1908,  0.3681,  0.2167,  0.7479,  0.8069],
        [ 1.1270, -0.3709, -1.4011,  0.2764,  0.5940, -1.9392,  0.5397,  2.4344],
        [ 0.6399,  1.7153,  0.4439, -0.5215,  0.6208,  1.2082,  1.2197, -0.8122],
        [ 1.3218, -0.0295, -0.0727,  0.9692,  0.7292, -0.2271, -0.8728,  1.8624],
        [ 0.1222,  0.6066, -1.6082, -0.9781,  1.0017,  0.3940, -0.3352, -0.5952]])


In [6]:
target=torch.randn(6,8).softmax(dim=1)
print(target)


In [7]:
loss=nn.CrossEntropyLoss()
print(loss(input,target))


tensor(2.4166)
