In [1]:
# PyTorch张量索引操作学习笔记
# 涵盖:基础索引、切片索引、列表索引、布尔索引(条件筛选)
import torch

In [2]:
# 创建测试张量
# shape:(3,5,4) 可理解为3个5x4的矩阵
# 元素范围:[1,10)的随机整数
# 应用:模拟批次数据(batch=3, seq_len=5, feature_dim=4)
tensor1= torch.randint(1,10,(3,5,4))
print(tensor1)

tensor([[[6, 4, 5, 8],
         [2, 7, 9, 5],
         [1, 4, 9, 8],
         [4, 7, 4, 2],
         [9, 8, 3, 9]],

        [[9, 4, 9, 2],
         [6, 5, 1, 1],
         [3, 3, 5, 1],
         [1, 7, 1, 2],
         [9, 1, 9, 3]],

        [[8, 1, 9, 9],
         [2, 8, 9, 7],
         [5, 1, 3, 9],
         [9, 3, 1, 3],
         [8, 1, 5, 6]]])


In [3]:
# 1. 基础索引(整数索引)
# 类似Python列表索引,但支持多维
# tensor[i,j,k]表示第i个矩阵的第j行第k列
# 冒号:表示该维度全选
# 应用:提取特定位置的元素、批次中的某一样本

# 提取单个元素:tensor1[2,1,3]→第2个矩阵第1行第3列
print(tensor1[2,1,3])  # 返回标量

# 提取一列:tensor1[:,2,3]→所有3个矩阵的第2行第3列
print(tensor1[:,2,3])  # 返回(3,)一维张量

# 提取一行:tensor1[:,3]→所有3个矩阵的第3行
print(tensor1[:,3])  # 返回(3,4)二维张量

tensor(7)
tensor([8, 1, 9])
tensor([[4, 7, 4, 2],
        [1, 7, 1, 2],
        [9, 3, 1, 3]])


In [4]:
# 2. 范围索引(切片)
# 语法:start:end:step, 类似Python列表切片
# start缺省为0, end缺省为长度, step缺省为1
# 注意:end不包含在范围内([ , ))
# 应用:提取子序列、数据分块处理

# tensor1[1:]→从第1个矩阵开始到末尾
# 结果:(3,5,4)→(2,5,4)只保留后2个矩阵
print(tensor1[1:])  # shape:(2,5,4)

tensor([[[9, 4, 9, 2],
         [6, 5, 1, 1],
         [3, 3, 5, 1],
         [1, 7, 1, 2],
         [9, 1, 9, 3]],

        [[8, 1, 9, 9],
         [2, 8, 9, 7],
         [5, 1, 3, 9],
         [9, 3, 1, 3],
         [8, 1, 5, 6]]])


In [5]:
# 多维切片
# tensor1[-1:,1:4]→最后一个矩阵,取第1-3行
# -1表示最后一个,1:4表示索引[1,2,3](不含4)
# 结果:(3,5,4)→(1,3,4)只保留1个矩阵的3行
print(tensor1[-1:,1:4])  # shape:(1,3,4)

tensor([[[2, 8, 9, 7],
         [5, 1, 3, 9],
         [9, 3, 1, 3]]])


In [6]:
# 3. 列表索引(花式索引)
# 使用列表指定要提取的索引位置
# tensor[[i1,i2],[j1,j2]]→提取(i1,j1)和(i2,j2)位置的元素
# 应用:不规则采样、根据索引列表提取数据

# 一维列表索引:tensor1[[1,2,0],[0,1,2]]
# 提取:tensor1[1,0], tensor1[2,1], tensor1[0,2]
# 即第1个矩阵的第0行,第2个矩阵的第1行,第0个矩阵的第2行
print(tensor1[[1,2,0],[0,1,2]])  # 迓回(3,4)

# 二维列表索引:tensor1[[[0],[1]],[0,1,2]]
# 广播机制:[[0],[1]](2,1)与[0,1,2](3,)广播为(2,3)
# 提取:tensor1[0,[0,1,2]]和tensor1[1,[0,1,2]]
# 即第0个矩阵的第[0,1,2]行和第1个矩阵的第[0,1,2]行
print(tensor1[[[0],[1]],[0,1,2]])  # 返回(2,3,4)

tensor([[9, 4, 9, 2],
        [2, 8, 9, 7],
        [1, 4, 9, 8]])
tensor([[[6, 4, 5, 8],
         [2, 7, 9, 5],
         [1, 4, 9, 8]],

        [[9, 4, 9, 2],
         [6, 5, 1, 1],
         [3, 3, 5, 1]]])


In [7]:
# 4. 布尔索引(条件筛选)
# 使用布尔张量(True/False)作为索引
# tensor[mask]提取mask为True位置对应的元素
# 应用:条件筛选、异常值检测、数据清洗

# 场景1:选取符合条件的行
# 条件:每行的首元素([:,i,0])>5
mask = tensor1[:,:,0]>5  # shape:(3,5),对每个矩阵的5行判断
print(mask)  # True/False矩阵

# tensor1[mask]提取所有mask=True对应的行
# 结果:将符合条件的行拼接成(n,4),n为True的数量
print(tensor1[mask])  # shape:(n,4),n是True的个数

tensor([[ True, False, False, False,  True],
        [ True,  True, False, False,  True],
        [ True, False, False,  True,  True]])
tensor([[6, 4, 5, 8],
        [9, 8, 3, 9],
        [9, 4, 9, 2],
        [6, 5, 1, 1],
        [9, 1, 9, 3],
        [8, 1, 9, 9],
        [9, 3, 1, 3],
        [8, 1, 5, 6]])


In [8]:
# 场景2:选取所有的列,第二个元素大于5
# 条件:每列的第1个元素([:,1,:])>5
mask = tensor1[:,1,:]>5  # shape:(3,4),对每个矩阵的4列判断
print(mask)

# 因为需要按列筛选,先转置
# .mT:矩阵转置(只转置最后两维),将(3,5,4)→(3,4,5)
tensor2=tensor1.mT  # 列变成行
# tensor2[mask]提取符合条件的行,然后再转置回来
print(tensor2[mask].mT)  # 转置回来成为列

tensor([[False,  True,  True, False],
        [ True, False, False, False],
        [False,  True,  True,  True]])
tensor([[4, 5, 9, 1, 9, 9],
        [7, 9, 6, 8, 9, 7],
        [4, 9, 3, 1, 3, 9],
        [7, 4, 1, 3, 1, 3],
        [8, 3, 9, 1, 5, 6]])


In [9]:
# 场景3:选取符合条件的矩阵：(1,2)> 5
# 条件:第1行第2列的元素>5
mask = tensor1[:,1,2]>5  # shape:(3,),对3个矩阵判断
print(mask)  # [True, False, False]表示只有第0个矩阵符合

# tensor1[mask]提取mask=True的矩阵
# 结果:(m,5,4),m为True的个数
print(tensor1[mask])  # shape:(1,5,4)只有第0个矩阵

tensor([ True, False,  True])
tensor([[[6, 4, 5, 8],
         [2, 7, 9, 5],
         [1, 4, 9, 8],
         [4, 7, 4, 2],
         [9, 8, 3, 9]],

        [[8, 1, 9, 9],
         [2, 8, 9, 7],
         [5, 1, 3, 9],
         [9, 3, 1, 3],
         [8, 1, 5, 6]]])


In [10]:
# 场景4:选取所有大于5的元素
# 条件:每个元素>5
mask = tensor1>5  # shape:(3,5,4),每个元素对应一个True/False
print(mask)  # 显示哪些位置的元素>5

# tensor1[mask]提取所有mask=True的元素
# 结果:一维张量,包含所有符合条件的值
# 注意:不保持原始形状,直接展平
print(tensor1[mask])  # shape:(n,),n为>5的元素个数

tensor([[[ True, False, False,  True],
         [False,  True,  True, False],
         [False, False,  True,  True],
         [False,  True, False, False],
         [ True,  True, False,  True]],

        [[ True, False,  True, False],
         [ True, False, False, False],
         [False, False, False, False],
         [False,  True, False, False],
         [ True, False,  True, False]],

        [[ True, False,  True,  True],
         [False,  True,  True,  True],
         [False, False, False,  True],
         [ True, False, False, False],
         [ True, False, False,  True]]])
tensor([6, 8, 7, 9, 9, 8, 7, 9, 8, 9, 9, 9, 6, 7, 9, 9, 8, 9, 9, 8, 9, 7, 9, 9,
        8, 6])
