In [1]:
# PyTorch张量形状操作学习笔记
# 形状操作是深度学习中非常重要的技能,用于调整数据维度以匹配模型输入输出
# 包括:维度交换、重塑、维度增减、张量拼接等操作
import torch

## 1. 查看张量形状

In [2]:
# 创建一个三维张量用于演示
# shape=[2,3,6]可理解为: 2个样本,每个样本3行6列的矩阵
# 应用场景: 批次数据(batch_size=2, height=3, width=6)
tensor1 = torch.randint(1, 10, [2, 3, 6])
print("张量形状:", tensor1.shape)      # torch.Size([2, 3, 6])
print("张量维度数:", tensor1.ndim)     # 3 (三维张量)
print("张量元素总数:", tensor1.numel()) # 2*3*6=36
print("张量内容:\n", tensor1)

张量形状: torch.Size([2, 3, 6])
张量维度数: 3
张量元素总数: 36
张量内容:
 tensor([[[3, 2, 9, 1, 1, 8],
         [3, 2, 9, 3, 9, 6],
         [7, 8, 2, 9, 7, 1]],

        [[2, 5, 4, 5, 3, 4],
         [7, 7, 8, 3, 8, 5],
         [7, 7, 8, 6, 1, 2]]])


## 2. 维度交换操作

In [3]:
# transpose(dim0, dim1): 交换两个指定维度
# 应用: 矩阵转置、调整通道顺序(如NCHW↔NHWC)
# 示例: shape=[2,3,6]交换维度1和2→shape=[2,6,3]
# 注意: transpose只能交换两个维度,多维交换需用permute
tensor2 = tensor1.transpose(1, 2)  # 交换第1维(3)和第2维(6)
print("原始形状:", tensor1.shape)    # torch.Size([2, 3, 6])
print("交换后形状:", tensor2.shape)  # torch.Size([2, 6, 3])
print("交换后内容:\n", tensor2)

原始形状: torch.Size([2, 3, 6])
交换后形状: torch.Size([2, 6, 3])
交换后内容:
 tensor([[[3, 3, 7],
         [2, 2, 8],
         [9, 9, 2],
         [1, 3, 9],
         [1, 9, 7],
         [8, 6, 1]],

        [[2, 7, 7],
         [5, 7, 7],
         [4, 8, 8],
         [5, 3, 6],
         [3, 8, 1],
         [4, 5, 2]]])


In [4]:
# .T: 二维张量的转置快捷方式(等价于transpose(0,1))
# 应用: 矩阵转置、线性代数运算
# 注意: .T只适用于二维张量,高维张量会交换前两维
matrix = torch.randint(1, 10, [3, 4])  # 3x4矩阵
print("原始矩阵形状:", matrix.shape)    # torch.Size([3, 4])
print("转置后形状:", matrix.T.shape)    # torch.Size([4, 3])
print("原始矩阵:\n", matrix)
print("转置矩阵:\n", matrix.T)

原始矩阵形状: torch.Size([3, 4])
转置后形状: torch.Size([4, 3])
原始矩阵:
 tensor([[2, 1, 5, 8],
        [1, 1, 7, 3],
        [4, 8, 1, 3]])
转置矩阵:
 tensor([[2, 1, 4],
        [1, 1, 8],
        [5, 7, 1],
        [8, 3, 3]])


In [5]:
# permute(*dims): 重新排列所有维度
# 参数: 新维度的排列顺序(必须包含所有维度)
# 应用: 图像格式转换(CHW→HWC)、调整批次维度顺序
# 示例: shape=[2,3,6], permute(2,0,1)→维度顺序变为[第2维,第0维,第1维]→shape=[6,2,3]
tensor3 = tensor1.permute(2, 0, 1)  # 将维度重排为[6,2,3]
print("原始形状:", tensor1.shape)    # torch.Size([2, 3, 6])
print("permute后形状:", tensor3.shape) # torch.Size([6, 2, 3])
print("permute后内容:\n", tensor3)

原始形状: torch.Size([2, 3, 6])
permute后形状: torch.Size([6, 2, 3])
permute后内容:
 tensor([[[3, 3, 7],
         [2, 7, 7]],

        [[2, 2, 8],
         [5, 7, 7]],

        [[9, 9, 2],
         [4, 8, 8]],

        [[1, 3, 9],
         [5, 3, 6]],

        [[1, 9, 7],
         [3, 8, 1]],

        [[8, 6, 1],
         [4, 5, 2]]])


## 3. 张量重塑操作

In [6]:
# reshape(*shape): 改变张量形状(不改变元素顺序和总数)
# 规则: 新形状的元素总数必须等于原形状元素总数
# 应用: 全连接层输入展平、调整批次大小
# 示例: [2,3,6]共36个元素→可reshape为[2,18]、[6,6]、[36]等
# 技巧: 可用-1让PyTorch自动推断该维度大小
tensor4 = tensor1.reshape(2, 18)  # 2x3x6=36元素→reshape为2x18
print("原始形状:", tensor1.shape)   # torch.Size([2, 3, 6])
print("reshape后形状:", tensor4.shape) # torch.Size([2, 18])
print("reshape后内容:\n", tensor4)

原始形状: torch.Size([2, 3, 6])
reshape后形状: torch.Size([2, 18])
reshape后内容:
 tensor([[3, 2, 9, 1, 1, 8, 3, 2, 9, 3, 9, 6, 7, 8, 2, 9, 7, 1],
        [2, 5, 4, 5, 3, 4, 7, 7, 8, 3, 8, 5, 7, 7, 8, 6, 1, 2]])


In [7]:
# reshape使用-1自动推断维度
# -1表示: 根据其他维度和总元素数自动计算该维度大小
# 示例: [2,3,6]共36元素, reshape(3,-1)→PyTorch计算-1位置为36/3=12
tensor5 = tensor1.reshape(3, -1)  # 自动计算为[3,12]
print("reshape(3,-1)形状:", tensor5.shape)  # torch.Size([3, 12])
tensor6 = tensor1.reshape(-1)     # 展平为一维向量
print("reshape(-1)形状:", tensor6.shape)    # torch.Size([36])

reshape(3,-1)形状: torch.Size([3, 12])
reshape(-1)形状: torch.Size([36])


In [8]:
# view(*shape): 类似reshape,但要求张量内存连续
# 区别: view要求内存连续(contiguous),reshape会在必要时复制数据
# 性能: view更快(不复制数据),但有内存连续性要求
# 检查: 用is_contiguous()检查内存是否连续
tensor5 = tensor1  # 直接赋值,内存连续
print("tensor5是否内存连续:", tensor5.is_contiguous())  # True
print("view操作成功:", tensor5.view(2, 18).shape)      # torch.Size([2, 18])

tensor5是否内存连续: True
view操作成功: torch.Size([2, 18])


In [9]:
# 处理非连续内存的张量
# transpose等操作会导致内存不连续,此时view会报错
# 解决: 先调用contiguous()使内存连续,再使用view
tensor6 = tensor1.T  # 转置后内存不连续
print("tensor6是否内存连续:", tensor6.is_contiguous())  # False
# tensor6.view(6, 6)  # 这行会报错:RuntimeError

# 使用contiguous()转为连续内存
tensor6 = tensor6.contiguous()  # 复制数据使内存连续
print("contiguous后是否连续:", tensor6.is_contiguous())  # True
print("view操作成功:", tensor6.view(-1, 18).shape)      # 现在可以用view了

tensor6是否内存连续: False
contiguous后是否连续: True
view操作成功: torch.Size([2, 18])


C:\Users\lenovo\AppData\Local\Temp\ipykernel_76828\874988388.py:4: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\TensorShape.cpp:4483.)
  tensor6 = tensor1.T  # 转置后内存不连续


In [10]:
# flatten(start_dim, end_dim): 展平指定维度范围
# 参数: start_dim(起始维度), end_dim(结束维度,默认-1表示最后一维)
# 应用: 卷积层输出展平后输入全连接层
# 示例: [2,3,6]从dim=1开始展平→[2, 3*6]=[2,18]
tensor7 = tensor1.flatten(start_dim=1)  # 保持dim0,展平后续维度
print("flatten(1)后形状:", tensor7.shape)  # torch.Size([2, 18])
tensor8 = tensor1.flatten()  # 全部展平为一维
print("flatten()后形状:", tensor8.shape)   # torch.Size([36])

flatten(1)后形状: torch.Size([2, 18])
flatten()后形状: torch.Size([36])


## 4. 维度增减操作

In [11]:
# unsqueeze(dim): 在指定位置增加一个大小为1的维度
# 参数: dim(插入位置,可为负数)
# 应用: 增加batch维度、扩展维度以匹配广播规则
# 示例: [3]→unsqueeze(0)→[1,3], unsqueeze(1)→[3,1]
tensor1 = torch.tensor([1, 2, 3])
print("原始形状:", tensor1.shape)  # torch.Size([3])

tensor2 = tensor1.unsqueeze(0)  # 在第0维插入
print("unsqueeze(0)形状:", tensor2.shape)  # torch.Size([1, 3]) - 行向量
print("unsqueeze(0)内容:", tensor2)

tensor3 = tensor1.unsqueeze(1)  # 在第1维插入
print("unsqueeze(1)形状:", tensor3.shape)  # torch.Size([3, 1]) - 列向量
print("unsqueeze(1)内容:\n", tensor3)

原始形状: torch.Size([3])
unsqueeze(0)形状: torch.Size([1, 3])
unsqueeze(0)内容: tensor([[1, 2, 3]])
unsqueeze(1)形状: torch.Size([3, 1])
unsqueeze(1)内容:
 tensor([[1],
        [2],
        [3]])


In [12]:
# unsqueeze_(): 原地操作版本(会修改原张量)
# 区别: unsqueeze()返回新张量, unsqueeze_()直接修改原张量
# 注意: 原地操作更节省内存,但会改变原张量
tensor4 = torch.tensor([1, 2, 3])
print("原地操作前:", tensor4.shape)      # torch.Size([3])
tensor4.unsqueeze_(dim=0)  # 直接修改tensor4
print("原地操作后:", tensor4.shape)      # torch.Size([1, 3])
print("tensor4现在是:", tensor4)

原地操作前: torch.Size([3])
原地操作后: torch.Size([1, 3])
tensor4现在是: tensor([[1, 2, 3]])


In [13]:
# squeeze(dim): 移除大小为1的维度
# 参数: dim(可选,指定移除哪个维度;不指定则移除所有大小为1的维度)
# 应用: 移除冗余维度、降维操作
# 示例: [1,3,1]→squeeze()→[3], squeeze(0)→[3,1]
tensor5 = torch.tensor([[[1, 2, 3]]])  # shape=[1,1,3]
print("原始形状:", tensor5.shape)  # torch.Size([1, 1, 3])

tensor6 = tensor5.squeeze()  # 移除所有大小为1的维度
print("squeeze()形状:", tensor6.shape)  # torch.Size([3])

tensor7 = tensor5.squeeze(0)  # 只移除第0维
print("squeeze(0)形状:", tensor7.shape)  # torch.Size([1, 3])

原始形状: torch.Size([1, 1, 3])
squeeze()形状: torch.Size([3])
squeeze(0)形状: torch.Size([1, 3])


## 5. 张量拼接操作

In [14]:
# torch.cat(tensors, dim): 沿指定维度拼接张量
# 参数: tensors(张量列表/元组), dim(拼接维度)
# 要求: 除拼接维度外,其他维度大小必须相同
# 应用: 合并批次数据、特征拼接
# 示例: 两个[2,3]沿dim=0拼接→[4,3], 沿dim=1拼接→[2,6]
tensor1 = torch.tensor([[1, 2, 3], [4, 5, 6]])    # shape=[2,3]
tensor2 = torch.tensor([[7, 8, 9], [10, 11, 12]]) # shape=[2,3]

# 沿第0维(行)拼接 - 增加行数
tensor3 = torch.cat((tensor1, tensor2), dim=0)
print("沿dim=0拼接:\n", tensor3)
print("拼接后形状:", tensor3.shape)  # torch.Size([4, 3])

# 沿第1维(列)拼接 - 增加列数
tensor4 = torch.cat((tensor1, tensor2), dim=1)
print("沿dim=1拼接:\n", tensor4)
print("拼接后形状:", tensor4.shape)  # torch.Size([2, 6])

沿dim=0拼接:
 tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])
拼接后形状: torch.Size([4, 3])
沿dim=1拼接:
 tensor([[ 1,  2,  3,  7,  8,  9],
        [ 4,  5,  6, 10, 11, 12]])
拼接后形状: torch.Size([2, 6])


In [15]:
# torch.stack(tensors, dim): 沿新维度堆叠张量
# 区别cat: cat在现有维度拼接, stack创建新维度
# 要求: 所有张量形状必须完全相同
# 应用: 批次数据组合、时序数据堆叠
# 示例: 两个[4,3,5]沿dim=0堆叠→[2,4,3,5], 沿dim=1堆叠→[4,2,3,5]
tensor1 = torch.randint(1, 10, [4, 3, 5])  # shape=[4,3,5]
tensor2 = torch.randint(1, 10, [4, 3, 5])  # shape=[4,3,5]

# 在第0维堆叠 - 创建新的批次维度
tensor3 = torch.stack([tensor1, tensor2], dim=0)
print("沿dim=0堆叠形状:", tensor3.shape)  # torch.Size([2, 4, 3, 5])

# 在第1维堆叠 - 在第1维位置插入新维度
tensor4 = torch.stack([tensor1, tensor2], dim=1)
print("沿dim=1堆叠形状:", tensor4.shape)  # torch.Size([4, 2, 3, 5])

沿dim=0堆叠形状: torch.Size([2, 4, 3, 5])
沿dim=1堆叠形状: torch.Size([4, 2, 3, 5])


In [16]:
# cat vs stack 对比示例
# cat: 在现有维度上拼接,不增加维度数
# stack: 创建新维度进行堆叠,维度数+1
a = torch.tensor([1, 2, 3])  # shape=[3]
b = torch.tensor([4, 5, 6])  # shape=[3]

cat_result = torch.cat([a, b], dim=0)
print("cat结果:", cat_result)           # tensor([1,2,3,4,5,6])
print("cat结果形状:", cat_result.shape) # torch.Size([6])

stack_result = torch.stack([a, b], dim=0)
print("stack结果:\n", stack_result)     # tensor([[1,2,3],[4,5,6]])
print("stack结果形状:", stack_result.shape) # torch.Size([2, 3])

cat结果: tensor([1, 2, 3, 4, 5, 6])
cat结果形状: torch.Size([6])
stack结果:
 tensor([[1, 2, 3],
        [4, 5, 6]])
stack结果形状: torch.Size([2, 3])


## 6. 张量分割操作

In [17]:
# torch.chunk(tensor, chunks, dim): 将张量分割为指定数量的块
# 参数: tensor(待分割张量), chunks(分割块数), dim(分割维度)
# 规则: 如果不能均分,最后一块会较小
# 应用: 多GPU训练数据分配、大批次数据分块处理
tensor1 = torch.arange(10)  # tensor([0,1,2,3,4,5,6,7,8,9])
chunks = torch.chunk(tensor1, 3, dim=0)  # 分成3块
print("分割成3块:")
for i, chunk in enumerate(chunks):
    print(f"  块{i}: {chunk}")  # [0,1,2,3], [4,5,6,7], [8,9]

分割成3块:
  块0: tensor([0, 1, 2, 3])
  块1: tensor([4, 5, 6, 7])
  块2: tensor([8, 9])


In [18]:
# torch.split(tensor, split_size_or_sections, dim): 按指定大小分割
# 参数: split_size_or_sections(整数或列表)
#       - 整数: 每块的大小
#       - 列表: 每块的具体大小
# 应用: 按需分割数据、多任务学习特征分离
tensor2 = torch.arange(10)

# 按固定大小分割
splits1 = torch.split(tensor2, 3, dim=0)  # 每块大小3
print("固定大小分割:")
for i, s in enumerate(splits1):
    print(f"  块{i}: {s}")  # [0,1,2], [3,4,5], [6,7,8], [9]

# 按列表指定每块大小
splits2 = torch.split(tensor2, [2, 3, 5], dim=0)  # 分别为2,3,5大小
print("\n自定义大小分割:")
for i, s in enumerate(splits2):
    print(f"  块{i}: {s}")  # [0,1], [2,3,4], [5,6,7,8,9]

固定大小分割:
  块0: tensor([0, 1, 2])
  块1: tensor([3, 4, 5])
  块2: tensor([6, 7, 8])
  块3: tensor([9])

自定义大小分割:
  块0: tensor([0, 1])
  块1: tensor([2, 3, 4])
  块2: tensor([5, 6, 7, 8, 9])


## 7. 张量重复操作

In [19]:
# repeat(*sizes): 沿各维度重复张量
# 参数: 各维度的重复次数(长度必须≥张量维度数)
# 应用: 数据增强、广播操作的显式实现
# 示例: [2,3]repeat(2,3)→沿dim0重复2次,dim1重复3次→[4,9]
tensor1 = torch.tensor([[1, 2], [3, 4]])  # shape=[2,2]
tensor2 = tensor1.repeat(2, 3)  # 沿dim0重复2次,dim1重复3次
print("原始张量:\n", tensor1)
print("repeat(2,3)形状:", tensor2.shape)  # torch.Size([4, 6])
print("repeat后张量:\n", tensor2)

原始张量:
 tensor([[1, 2],
        [3, 4]])
repeat(2,3)形状: torch.Size([4, 6])
repeat后张量:
 tensor([[1, 2, 1, 2, 1, 2],
        [3, 4, 3, 4, 3, 4],
        [1, 2, 1, 2, 1, 2],
        [3, 4, 3, 4, 3, 4]])


In [20]:
# repeat_interleave(repeats, dim): 在指定维度上交错重复元素
# 区别repeat: repeat整体重复, repeat_interleave逐元素重复
# 应用: 上采样、标签扩展
# 示例: [1,2,3]repeat_interleave(2)→[1,1,2,2,3,3]
tensor3 = torch.tensor([1, 2, 3])
tensor4 = tensor3.repeat_interleave(2)  # 每个元素重复2次
print("原始张量:", tensor3)  # tensor([1, 2, 3])
print("repeat_interleave(2):", tensor4)  # tensor([1, 1, 2, 2, 3, 3])

# 二维张量的repeat_interleave
tensor5 = torch.tensor([[1, 2], [3, 4]])
tensor6 = tensor5.repeat_interleave(2, dim=0)  # 沿行重复
print("\n原始矩阵:\n", tensor5)
print("沿dim=0 repeat_interleave(2):\n", tensor6)
# 结果: [[1,2], [1,2], [3,4], [3,4]]

原始张量: tensor([1, 2, 3])
repeat_interleave(2): tensor([1, 1, 2, 2, 3, 3])

原始矩阵:
 tensor([[1, 2],
        [3, 4]])
沿dim=0 repeat_interleave(2):
 tensor([[1, 2],
        [1, 2],
        [3, 4],
        [3, 4]])
