In [7]:
import torch

In [8]:
# 定义数据
# x: 标量输入值，不参与梯度计算
# y: 目标值，形状为(1,1)的二维张量
x=torch.tensor(10.0)
y=torch.tensor([[3.0]])
print('输入值 x:', x)
print('目标值 y:', y)


tensor(10.)
tensor([[3.]])


In [9]:
# 初始化参数
# w: 权重参数，形状(1,1)，requires_grad=True表示需要计算梯度
# b: 偏置参数，形状(1,1)，同样需要梯度计算
# rand()生成[0,1)区间均匀分布的随机数
w=torch.rand(1,1,requires_grad=True)
b=torch.rand(1,1,requires_grad=True)


In [10]:
# 前向传播，得到输出
# z = w*x + b: 线性变换，构建计算图
# 由于w和b设置了requires_grad=True，z会记录grad_fn(梯度函数)
z=w*x+b
print('前向传播输出 z:', z)


tensor([[8.0893]], grad_fn=<AddBackward0>)


In [11]:
# 检查张量的叶子节点属性
# is_leaf: True表示叶子节点(用户创建的张量)，False表示中间计算结果
# 只有叶子节点才能积累梯度(grad属性)
print('x.is_leaf (输入):', x.is_leaf)
print('w.is_leaf (权重):', w.is_leaf)
print('b.is_leaf (偏置):', b.is_leaf)
print('z.is_leaf (计算结果):', z.is_leaf)
print('y.is_leaf (目标值):', y.is_leaf)

True
True
True
False
True


In [12]:
# 设置损失函数
# MSELoss: 均方误差损失函数，计算预测值与真实值的平方差平均
# loss_value: 损失值，is_leaf=False因为它是计算图的终点
loss=torch.nn.MSELoss()
loss_value=loss(z,y)
print('损失值:', loss_value, '是否为叶子节点:', loss_value.is_leaf)


tensor(25.9005, grad_fn=<MseLossBackward0>) False


In [13]:
# 反向传播
# backward(): 从loss_value开始反向传播，自动计算所有requires_grad=True张量的梯度
# 梯度存储在对应张量的.grad属性中
loss_value.backward()


In [14]:
# 查看梯度
# w.grad: 权重w相对于loss的梯度∂L/∂w
# b.grad: 偏置b相对于loss的梯度∂L/∂b
# 梯度值用于指导参数更新方向
print('权重w的梯度:', w.grad)
print('偏置b的梯度:', b.grad)

tensor([[101.7851]])
tensor([[10.1785]])
