In [1]:
import torch
from win32print import PRINTER_ACCESS_ADMINISTER

In [2]:
# detach()方法演示
# x: 带梯度计算的张量，requires_grad=True
# y: 通过detach()分离得到的新张量，不参与梯度计算
x=torch.tensor(2.0,requires_grad=True)
y=x.detach()
print('原始张量 x:', x)
print('分离张量 y:', y)

tensor(2., requires_grad=True)
tensor(2.)


In [3]:
# 检查梯度计算属性
# requires_grad: True表示参与自动微分，False表示不参与
# detach()会创建新的张量，且requires_grad=False
print('x.requires_grad:', x.requires_grad)
print('y.requires_grad:', y.requires_grad)


True
False


In [4]:
print(id(x))
print(id(y))

2151817244304
2152064765136


In [5]:
print(x.untyped_storage().data_ptr())
print(y.untyped_storage().data_ptr())

5354683433088
5354683433088


In [6]:
# print(x)
# y.zero_()
# print(x)

In [7]:
# 分别对x和y进行后续计算
z1=x**2
z2=y**2
print(z1)
print(z2)

tensor(4., grad_fn=<PowBackward0>)
tensor(4.)


In [8]:
z1.sum().backward()

In [9]:
# z2.sum().backward()

In [10]:
x=torch.ones(2,2,requires_grad=True)
y=x*x
print(x)
print(y)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[1., 1.],
        [1., 1.]], grad_fn=<MulBackward0>)


In [11]:
# 分离y
u = y.detach()
print(u)


tensor([[1., 1.],
        [1., 1.]])


In [12]:
# 让u参与新张量计算
z=u*x

In [13]:
# 反向传播，计算所有梯度
z.sum().backward()

In [14]:
print(x.grad==u)

tensor([[True, True],
        [True, True]])
